### ISSUE TITLE
include "struct.h"

### ISSUE THREAD

**Issue by amirkourdi** [WJsjtu/socket-control#1]
fatal error: struct.h: No such file or directory
 #include "struct.h"

**Comment by WJsjtu** [comment]
@AmirKourdi Thank you for pointing out the error, I've fixed this error.

**Comment by amirkourdi** [comment]
still get error.

now it is not recognized __NR_socketcall



kourdi@ubuntu:~/kernel_module$ make
make -C /lib/modules/4.8.0-22-generic/build SUBDIRS=/home/kourdi/kernel_module modules
make[1]: Entering directory '/usr/src/linux-headers-4.8.0-22-generic'
  CC [M]  /home/kourdi/kernel_module/sdthook.o
/home/kourdi/kernel_module/sdthook.c: In function 'connect_control_init':
/home/kourdi/kernel_module/sdthook.c:181:42: error: '__NR_socketcall' undeclared (first use in this function)
     orig_sys_socketcall = sys_call_table[__NR_socketcall];
                                          ^~~~~~~~~~~~~~~
/home/kourdi/kernel_module/sdthook.c:181:42: note: each undeclared identifier is reported only once for each function it appears in
/home/kourdi/kernel_module/sdthook.c:182:55: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     printk("[Module:init]: store the syscall : %x\n", (unsigned int)orig_sys_socketcall);
                                                       ^
/home/kourdi/kernel_module/sdthook.c:184:54: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     printk("[Module:init]: hack the syscall : %x\n", (unsigned int)hacked_sys_socketcall);
                                                      ^
/home/kourdi/kernel_module/sdthook.c: In function 'connect_control_exit':
/home/kourdi/kernel_module/sdthook.c:196:55: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     printk("[Module:exit]: reset the syscall : %x\n", (unsigned int)orig_sys_socketcall);
                                                       ^
/home/kourdi/kernel_module/sdthook.c:197:20: error: '__NR_socketcall' undeclared (first use in this function)
     sys_call_table[__NR_socketcall] = orig_sys_socketcall;
                    ^~~~~~~~~~~~~~~
scripts/Makefile.build:289: recipe for target '/home/kourdi/kernel_module/sdthook.o' failed
make[2]: *** [/home/kourdi/kernel_module/sdthook.o] Error 1
Makefile:1489: recipe for target '_module_/home/kourdi/kernel_module' failed
make[1]: *** [_module_/home/kourdi/kernel_module] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.8.0-22-generic'
Makefile:6: recipe for target 'default' failed
make: *** [default] Error 2
kourdi@ubuntu:~/kernel_module$







---

Amir Kourdi
m:

e:      amir_kourdi@hotmail.com<mailto:amir_kourdi@hotmail.com>


________________________________

**Comment by WJsjtu** [comment]
It seems that your platform is x64. however, the target platform for this demo is x86.  `__NR_socketcall ` is not defined in x64 include files, you may need to fix it by yourself.
Several warnings about `cast from pointer to integer of different size` is also caused by the same resaon. On x64 platform, you may also need `long` instead of `unsigned int` and `%lx` instead of `%x` for `sprintf` , `printk`.

So if you want to write more robust code you may need to deal with both x64 and x86 by some macros and other technique to handle such kind of differences. For example, in yesterday's [commit](https://github.com/WJsjtu/socket-control/commit/c424f03f466612be216cbbe2fd2993cfb3821366#diff-5fb8655871c5207eb39215f8a1fef1f6L59), I replaced `strict_strtoul` with `kstrtoul` since `strict_strtoul` is no longer defined in the current version of the kernel. And here is some of the information:
>strict_strtoul() was just a redefinition of kstrtoul() for a long time. From kernel version of 3.18, strict_strtoul() will not be defined at all. A compile time kernel version check is needed to
decide which function or macro can be used for a specific version of kernel.

Anyway, I hope all these can help you. But I have to admit that I've been long time away from kernel development, and I‘m now unfamiliar to related knowledge points. 
Anyway, good luck for you.

**Comment by WJsjtu** [comment]
`__NR_socketcall ` is declared in <linux/unistd.h>.
But it depends on system and compiler.
For my system `ubuntu-14.04.4-desktop-i386`, my result of `cpp -v`:
```
Using built-in specs.
COLLECT_GCC=cpp
Target: i686-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.3' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-i386/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-i386 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-i386 --with-arch-directory=i386 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-targets=all --enable-multiarch --disable-werror --with-arch-32=i686 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=i686-linux-gnu --host=i686-linux-gnu --target=i686-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
COLLECT_GCC_OPTIONS='-E' '-v' '-mtune=generic' '-march=i686'
 /usr/lib/gcc/i686-linux-gnu/4.8/cc1 -E -quiet -v -imultiarch i386-linux-gnu - -mtune=generic -march=i686 -fstack-protector -Wformat -Wformat-security
ignoring nonexistent directory "/usr/local/include/i386-linux-gnu"
ignoring nonexistent directory "/usr/lib/gcc/i686-linux-gnu/4.8/../../../../i686-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/i686-linux-gnu/4.8/include
 /usr/local/include
 /usr/lib/gcc/i686-linux-gnu/4.8/include-fixed
 /usr/include/i386-linux-gnu
 /usr/include
End of search list.
```

According to the include rules, I found /usr/include/linux/unistd.h. The file content is:
```
#ifndef _LINUX_UNISTD_H_
#define _LINUX_UNISTD_H_

/*
 * Include machine specific syscall numbers
 */
#include <asm/unistd.h>

#endif /* _LINUX_UNISTD_H_ */
```
So I kept on search where `asm/unistd.h` is, and finally found it in `usr/include/i386-linux-gnu/asm/unistd.h`, and its content is:
```
#ifndef _ASM_X86_UNISTD_H
#define _ASM_X86_UNISTD_H

/* x32 syscall flag bit */
#define __X32_SYSCALL_BIT	0x40000000

# ifdef __i386__
#  include <asm/unistd_32.h>
# elif defined(__ILP32__)
#  include <asm/unistd_x32.h>
# else
#  include <asm/unistd_64.h>
# endif

#endif /* _ASM_X86_UNISTD_H */
```
According to my system it is `<asm/unistd_x32.h>`, and I found the declaration:
`#define __NR_socketcall 102`
Also, I read the `<asm/unistd_x64.h>` next to it and could not find the declaration of `__NR_socketcall`.

This means if you want to run it on x64, you should fix this problem. 

And I had impression that `__NR_socketcall` refers to a set of syscalls, I used it for the sake of convenience. I wrote the control in [hacked_sys_socketcall](https://github.com/WJsjtu/socket-control/blob/master/kernel_module/sdthook.c#L87) function by using `switch-case` for `call`.
Maybe you need to split the different syscalls [here](https://github.com/WJsjtu/socket-control/blob/master/kernel_module/sdthook.c#L183) in the worst case.
